### ISSUE TITLE
I don't understand the code

### ISSUE THREAD

**Issue by ghost** [Ankit-29/webAgent#1]
Hi ~ @Ankit-29  
I'm looking for code to navigate the browser

I don't understand the code, can you tell me the mail

I'll be waiting : )

**Comment by Ankit-29** [comment]
Hi @Seung-hwan285 

You can refer to this blog [https://the-average-developer.medium.com/browser-detection-using-javascript-9fe59fee23b0](https://the-average-developer.medium.com/browser-detection-using-javascript-9fe59fee23b0)

Also if you need further help drop me a mail at **_iamankitkumar29@gmail.com_**

**Comment by ghost** [comment]
Thanks @Ankit-29  : ) !!
